import { IGame } from "./interface/IGame";

export const dataGame: IGame = {
    id: "12",
    title: "Программисты",
    categories: [
        {
            title: "Назад в прошлое",
            questions: [
                {
                    question: "Какое из современных устройсв современного компбютера соответвует <<складу Бэббиджа>>",
                    question_type: "text",
                    question_file: null,
                    answer: "Жесткий диск",
                    answer_type: "text",
                    answer_file: null,
                    points: 100,
                    isHidden: false,
                },
                {
                    question: "Как называется повторяющиеся операции в программе?",
                    question_type: "text",
                    question_file: null,
                    answer: "Цикл",
                    answer_type: "text",
                    answer_file: null,
                    points: 200,
                    isHidden: false,
                },
                {
                    question: "Как назывался карточки, на которых писался код для ЭВМ первого поколения?",
                    question_type: "text",
                    question_file: null,
                    answer: "Перфокарты",
                    answer_type: "text",
                    answer_file: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg/300px-%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg",
                    points: 300,
                    isHidden: false,
                },
                {
                    question: "Чем явдядасть программа <<Elk Cloner>> написанная Ричардом Скрента",
                    question_type: "text",
                    question_file: null,
                    answer: "Компьютерный вирус",
                    answer_type: "text",
                    answer_file: null,
                    points: 400,
                    isHidden: false,
                },
                {
                    question: "Какую фразу выводил самый опачный вирус при заражении компьюера?",
                    question_type: "text",
                    question_file: null,
                    answer: "I LOVE YOU",
                    answer_type: "img",
                    answer_file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVjTQ_0_q3T3IM2DtvbgZj5ain7Ali2nOnPjepW2Utg&s",
                    points: 500,
                    isHidden: false,
                }
            ]
        },
        {
            title: "Назад в прошлое",
            questions: [
                {
                    question: "Какое из современных устройсв современного компбютера соответвует <<складу Бэббиджа>>",
                    question_type: "text",
                    question_file: null,
                    answer: "Жесткий диск",
                    answer_type: "text",
                    answer_file: null,
                    points: 100,
                    isHidden: false,
                },
                {
                    question: "Как называется повторяющиеся операции в программе?",
                    question_type: "text",
                    question_file: null,
                    answer: "Цикл",
                    answer_type: "text",
                    answer_file: null,
                    points: 200,
                    isHidden: false,
                },
                {
                    question: "Как назывался карточки, на которых писался код для ЭВМ первого поколения?",
                    question_type: "text",
                    question_file: null,
                    answer: "Перфокарты",
                    answer_type: "text",
                    answer_file: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg/300px-%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg",
                    points: 300,
                    isHidden: false,
                },
                {
                    question: "Чем явдядасть программа <<Elk Cloner>> написанная Ричардом Скрента",
                    question_type: "text",
                    question_file: null,
                    answer: "Компьютерный вирус",
                    answer_type: "text",
                    answer_file: null,
                    points: 400,
                    isHidden: false,
                },
                {
                    question: "Какую фразу выводил самый опачный вирус при заражении компьюера?",
                    question_type: "text",
                    question_file: null,
                    answer: "I LOVE YOU",
                    answer_type: "img",
                    answer_file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVjTQ_0_q3T3IM2DtvbgZj5ain7Ali2nOnPjepW2Utg&s",
                    points: 500,
                    isHidden: false,
                }
            ]
        },
        {
            title: "Назад в прошлое",
            questions: [
                {
                    question: "Какое из современных устройсв современного компбютера соответвует <<складу Бэббиджа>>",
                    question_type: "text",
                    question_file: null,
                    answer: "Жесткий диск",
                    answer_type: "text",
                    answer_file: null,
                    points: 100,
                    isHidden: false,
                },
                {
                    question: "Как называется повторяющиеся операции в программе?",
                    question_type: "text",
                    question_file: null,
                    answer: "Цикл",
                    answer_type: "text",
                    answer_file: null,
                    points: 200,
                    isHidden: false,
                },
                {
                    question: "Как назывался карточки, на которых писался код для ЭВМ первого поколения?",
                    question_type: "text",
                    question_file: null,
                    answer: "Перфокарты",
                    answer_type: "text",
                    answer_file: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg/300px-%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg",
                    points: 300,
                    isHidden: false,
                },
                {
                    question: "Чем явдядасть программа <<Elk Cloner>> написанная Ричардом Скрента",
                    question_type: "text",
                    question_file: null,
                    answer: "Компьютерный вирус",
                    answer_type: "text",
                    answer_file: null,
                    points: 400,
                    isHidden: false,
                },
                {
                    question: "Какую фразу выводил самый опачный вирус при заражении компьюера?",
                    question_type: "text",
                    question_file: null,
                    answer: "I LOVE YOU",
                    answer_type: "img",
                    answer_file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVjTQ_0_q3T3IM2DtvbgZj5ain7Ali2nOnPjepW2Utg&s",
                    points: 500,
                    isHidden: false,
                }
            ]
        },
        {
            title: "Назад в прошлое",
            questions: [
                {
                    question: "Какое из современных устройсв современного компбютера соответвует <<складу Бэббиджа>>",
                    question_type: "text",
                    question_file: null,
                    answer: "Жесткий диск",
                    answer_type: "text",
                    answer_file: null,
                    points: 100,
                    isHidden: false,
                },
                {
                    question: "Как называется повторяющиеся операции в программе?",
                    question_type: "text",
                    question_file: null,
                    answer: "Цикл",
                    answer_type: "text",
                    answer_file: null,
                    points: 200,
                    isHidden: false,
                },
                {
                    question: "Как назывался карточки, на которых писался код для ЭВМ первого поколения?",
                    question_type: "text",
                    question_file: null,
                    answer: "Перфокарты",
                    answer_type: "text",
                    answer_file: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg/300px-%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg",
                    points: 300,
                    isHidden: false,
                },
                {
                    question: "Чем явдядасть программа <<Elk Cloner>> написанная Ричардом Скрента",
                    question_type: "text",
                    question_file: null,
                    answer: "Компьютерный вирус",
                    answer_type: "text",
                    answer_file: null,
                    points: 400,
                    isHidden: false,
                },
                {
                    question: "Какую фразу выводил самый опачный вирус при заражении компьюера?",
                    question_type: "text",
                    question_file: null,
                    answer: "I LOVE YOU",
                    answer_type: "img",
                    answer_file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVjTQ_0_q3T3IM2DtvbgZj5ain7Ali2nOnPjepW2Utg&s",
                    points: 500,
                    isHidden: false,
                }
            ]
        },
        {
            title: "Назад в прошлое",
            questions: [
                {
                    question: "Какое из современных устройсв современного компбютера соответвует <<складу Бэббиджа>>",
                    question_type: "text",
                    question_file: null,
                    answer: "Жесткий диск",
                    answer_type: "text",
                    answer_file: null,
                    points: 100,
                    isHidden: false,
                },
                {
                    question: "Как называется повторяющиеся операции в программе?",
                    question_type: "text",
                    question_file: null,
                    answer: "Цикл",
                    answer_type: "text",
                    answer_file: null,
                    points: 200,
                    isHidden: false,
                },
                {
                    question: "Как назывался карточки, на которых писался код для ЭВМ первого поколения?",
                    question_type: "text",
                    question_file: null,
                    answer: "Перфокарты",
                    answer_type: "text",
                    answer_file: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg/300px-%D0%9F%D0%B5%D1%80%D1%84%D0%BE%D0%BA%D0%B0%D1%80%D1%82%D0%B0.jpg",
                    points: 300,
                    isHidden: false,
                },
                {
                    question: "Чем явдядасть программа <<Elk Cloner>> написанная Ричардом Скрента",
                    question_type: "text",
                    question_file: null,
                    answer: "Компьютерный вирус",
                    answer_type: "text",
                    answer_file: null,
                    points: 400,
                    isHidden: false,
                },
                {
                    question: "Какую фразу выводил самый опачный вирус при заражении компьюера?",
                    question_type: "text",
                    question_file: null,
                    answer: "I LOVE YOU",
                    answer_type: "img",
                    answer_file: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVjTQ_0_q3T3IM2DtvbgZj5ain7Ali2nOnPjepW2Utg&s",
                    points: 500,
                    isHidden: false,
                }
            ]
        },
    ]
}